[package]
name = "qnighy-swc-plugin-dedent"
publish = false
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.155"
swc_core = { version = "0.75.22", features = ["ecma_plugin_transform"] }
