name: build and test (JS)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install yarn dependencies
      run: yarn install --immutable
    - name: Build
      run: yarn build:js
    - name: Run tests
      run: yarn test:js:nobuild
    - name: Lint
      run: yarn lint:js:nobuild --max-warnings 0
    - name: Check formatting
      run: yarn fmt:js
    - name: Check formatting
      run: yarn fmt:js
